version: '3'

networks:
  default:
    name: ${PROJECT_NAME:-project}-network
    driver: bridge

volumes:
  db-dev:

services:
  php:
    build:
      context: ./
      args:
        USER: ${USER:-user}
        PASSWORD: ${PASSWORD:-password}
    environment:
      - APACHE_RUN_USER=${USER:-user}
      - APACHE_RUN_GROUP=${USER:-user}
      - LC_CDPATH=/var/www/html
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-project}-php
    volumes:
      - ./:/var/www/html
    ports:
      - ${WEB_PORT:-10000}:80
    depends_on:
      - db
  
  db:
    image: mariadb:10.7
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-project}-db
    environment:
      MYSQL_DATABASE: ${DB_NAME:-db}
      MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD:-QWEasd123!}
      MYSQL_USER: ${USER:-user}
      MYSQL_PASSWORD: ${PASSWORD:-password}
    volumes:
      - db-dev:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-project}-phpmyadmin
    ports:
      - ${WEB_PORT_PHPMYADMIN:-8888}:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db